### ISSUE TITLE
Idea: CLI-standalone versions

### ISSUE THREAD

**Issue by fwolfst** [AlisterH/gwc#14]
As a CLI-person it would be awesome for me to have the denoise feature as a standalone cli-tool, where I could play with the parameters and have separate output files to compare (`gwc-denoise --power-floor 0.2 --input input-file.wav --output denoised_pow_0.2.wav`).

Unfortunately, due to resource limits and very rusty C-skills i cannot contribute. Feel free to close this issue.

**Comment by AlisterH** [comment]
Hi, there isn't a true standalone tool, but there is a CLI interface of sorts, which it sounds like you may not be aware of.  There is even a helper script for batch processing `gwcbatch`.
It should be easy enough to write a script to edit the settings file before running denoise from the command line.

The only thing to be aware of is that there is a minor bug affecting at least one of the tools when running from command line.  If I recall correctly there were bugs with several of the tools when running from command line, where it calculated the starting position wrong by one frame, so it is impossible to process an entire file from the command line.  I think I fixed it for at least one tool, but I never had time to track it down for at least one other, and I can't remember which one.  For a couple of years this has been the next thing on my list that I want to sort out "some day"!

**Comment by fwolfst** [comment]
> Hi, there isn't a true standalone tool, but there is a CLI interface of sorts, which it sounds like you may not be aware of. There is even a helper script for batch processing `gwcbatch`.

Oh thanks. Will look into that. 

>  For a couple of years this has been the next thing on my list that I want to sort out "some day"!

Been there. I anyway hope that soon new equipment arrives which should make my denoising workflow obsolete.

**Comment by AlisterH** [comment]
> If I recall correctly there were bugs with several of the tools when running from command line, where it calculated the starting position wrong by one frame, so it is impossible to process an entire file from the command line.

See #22.  The problematic functions are ones that people are likely not to need anyway.
