### ISSUE TITLE
Inconsistent punctuation for decimal values

### ISSUE THREAD

**Issue by fwolfst** [AlisterH/gwc#15]
Not sure if this has to do with my locale settings, but in e.g. the denoise settings, I have to enter values with a comma ("0,5") whereas the example denotes a dot ("0.5").
I guess its GTK taking care of (and thats a good thing), if not and indeed you need to put a comma instead of the dot, I can craft a PR for a documentation change.

```bash
$ locale   
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=

```

**Comment by AlisterH** [comment]
Hi, that is what your LC_NUMERIC is setting, isn't it?  If you change that you'll probably find dots work instead.
