### ISSUE TITLE
Fix for gtkledbar, failure to automake, etc

### ISSUE THREAD

**Issue by weltyj** [AlisterH/gwc#16]
(For those reading, Alister has resolved all my issues.  I needed to do an "autoreconf -i" and then configure worked perfectly, and the compile worked and the ledbars work as they are supposed to work.)

Hi Alister!

Jeff Welty here.   I use GWC still sometimes.

I am using linux Mint 19.3, and diving into my own code (not the github code, it is pre-automake version 0.21-20), after getting the development libs installed, running aclocal, autoconf, ./configure, gwc compiled with no issues, but running it would crash immediately with a segfault.

The problem was in the gtkledbar code and a GTK+ 2 call that is no longer supported.
Yesterday I just rewrote that code.  Not a completely transparent fix, the calls to initialize and set the led bar percentages have an additional argument.   The result looks identical to the past led bars, and is probably much more efficient too.

Who knows how much longer any of the GTK+ 2 gui will be supported though.   If GWC is to have a hope of a longer life it will have to get ported to the cairo calls.   Someone who knows what they are doing could likely do the port in a week.   I'm not that person, having zero experience with cairo.

I thought I'd add the fix to the current release here on github (0.22-4), and  found myself in the notorious automake battle, and losing the battle.

Given that GWC is already a dinosaur, I'd be tempted to remove the automake (which apparently only adds some smarts for the "help" function files?), have help simply pop up a link for the github web help page.

Either way (with or without automake), I think I can make the master branch compile by manually removing automake.  So I could make the appropriate changes to gwc.c, gtkledbar.c and gtkledbar.h and get those pushed to github.

What do you think about all that?

Cheers!
Jeff

**Comment by AlisterH** [comment]
Hi Jeff, I'm a little confused by all that.
1. Perhaps I just need to see your changes, because my immediate question is how there can be an issue with an unsupported gtk2 call when we have been building and running gwc successfully.  I did have to fix some things with the led bars already.  BTW there are people who think the ledbar is confusing and should be removed anyway because the playback apparently lags behind it.
2. you never released an 0.21-20; are there other changes you did after 0.21-19 that were never released?  I guess it would be good to see them; is that why you started with the old code, or was it just because you had build issues with the github code?
3. the build system could do with a big overhaul, if only someone more competent than me wanted to do it.  But I'm not keen on removing local help files or making changes that'll cause work for downstream packagers without a clear rationale.
I presume you're saying you have automake problems with my source, nothing to do with your new changes.  I thought the build system was working fairly well for other people, although I think on Arch they've found they need to use some special flags for the latest gcc or something.  
I'd be interested to see the problems you're getting; It doesn't sound like you've downloaded using git and not found the instructions to run `autoreconf -i`, which is what trips some people up.
4. I did look into what was required to port to GTK3 several years ago.  It seemed like it wouldn't be too hard, but I haven't been able to justify investing the time.

**Comment by AlisterH** [comment]
Yes, please do show us your changes.

**Comment by weltyj** [comment]
An update:

Sorry about the version confusion -- 0.21-20 is my current version, which is identical to 0.21-19.  I always updated my version number after a release to make sure I didn't overwrite a previous release.

After I stuck in my configure from 0.21-19 into the 0.22-4 version which I got directly from github, it compiled and the gtkledbar is no longer a problem, runs just fine.

Yes, playback does lag behind the ledbar and it is confusing.  Playback sends audio blocks to the alsa driver when it has room in the buffer.  The ledbar level is set when an audio block is sent to the buffer.   Back in the dark ages, the buffer wasn't large so there was good correspondence between the ledbar and the playback cursor.   I suspect now there's a much larger alsa buffer so the ledbar gets "ahead" of the actual playback.

Could be fixed by keeping track of the playback position and the levels for that position -- but, it is just fun eyecandy.  Given the audio waveform is displayed on the screen, the ledbar is actually redundant.  At the moment I am writing this I can't remember how the size of the waveform is determined.  I know the ledbar uses the maximum absolute value found in a playback block, but I seem to recall the waveform uses a different approach and may not show clipped audio.   I'll go have a look.  If it really is showing clipped audio, it's probably worth removing the ledbar (probably start with #ifdef-ing it out of the compile)

And thanks for the autoreconf -i tip.   I didn't see that in the INSTALL file from github.   I'll give that a try.

Nice to hear from you, thanks a bunch for getting GWC on github, you've been a good steward!

Cheers,
Jeff







On Monday, January 18, 2021, 11:17:12 AM PST, AlisterH <notifications@github.com> wrote: 







Hi Jeff, I'm a little confused by all that.

     
    1. Perhaps I just need to see your changes, because my immediate question is how there can be an issue with an unsupported gtk2 call when we have been building and running gwc successfully. I did have to fix some things with the led bars already. BTW there are people who think the ledbar is confusing and should be removed anyway because the playback apparently lags behind it.
    
    2. you never released an 0.21-20; are there other changes you did after 0.21-19 that were never released? I guess it would be good to see them; is that why you started with the old code, or was it just because you had build issues with the github code?
    
    3. the build system could do with a big overhaul, if only someone more competent than me wanted to do it. But I'm not keen on removing local help files or making changes that'll cause work for downstream packagers without a clear rationale.
I presume you're saying you have automake problems with my source, nothing to do with your new changes. I thought the build system was working fairly well for other people, although I think on Arch they've found they need to use some special flags for the latest gcc or something.
I'd be interested to see the problems you're getting; It doesn't sound like you've downloaded using git and not found the instructions to run autoreconf -i, which is what trips some people up.
    
    4. I did look into what was required to port to GTK3 several years ago. It seemed like it wouldn't be too hard, but I haven't been able to justify investing the time.

**Comment by weltyj** [comment]
autoreconf -i worked like a charm.   Clean compile with the stock 0.22-4 from github.

I'll dig into whether the audio waveform on screen shows clipped audio.






On Monday, January 18, 2021, 11:17:12 AM PST, AlisterH <notifications@github.com> wrote: 







Hi Jeff, I'm a little confused by all that.

     
    1. Perhaps I just need to see your changes, because my immediate question is how there can be an issue with an unsupported gtk2 call when we have been building and running gwc successfully. I did have to fix some things with the led bars already. BTW there are people who think the ledbar is confusing and should be removed anyway because the playback apparently lags behind it.
    
    2. you never released an 0.21-20; are there other changes you did after 0.21-19 that were never released? I guess it would be good to see them; is that why you started with the old code, or was it just because you had build issues with the github code?
    
    3. the build system could do with a big overhaul, if only someone more competent than me wanted to do it. But I'm not keen on removing local help files or making changes that'll cause work for downstream packagers without a clear rationale.
I presume you're saying you have automake problems with my source, nothing to do with your new changes. I thought the build system was working fairly well for other people, although I think on Arch they've found they need to use some special flags for the latest gcc or something.
I'd be interested to see the problems you're getting; It doesn't sound like you've downloaded using git and not found the instructions to run autoreconf -i, which is what trips some people up.
    
    4. I did look into what was required to port to GTK3 several years ago. It seemed like it wouldn't be too hard, but I haven't been able to justify investing the time.

**Comment by weltyj** [comment]
And -- the audio waveform does display the maximum values, so it will show audio clipping.   I was a little foggy on that, there was an iteration that was displaying the RMS values for all audio samples contained in that pixel position of the waveform.

So, ledbar probably should either be removed, or tied to the audio values under the cursor.  Removing is easy.  

If you think it's worth the eyecandy, I can look at tying the ledbar value to the cursor position.  I could go either way, but lean a little towards the eyecandy.

Cheers,
Jeff






On Monday, January 18, 2021, 11:17:12 AM PST, AlisterH <notifications@github.com> wrote: 







Hi Jeff, I'm a little confused by all that.

     
    1. Perhaps I just need to see your changes, because my immediate question is how there can be an issue with an unsupported gtk2 call when we have been building and running gwc successfully. I did have to fix some things with the led bars already. BTW there are people who think the ledbar is confusing and should be removed anyway because the playback apparently lags behind it.
    
    2. you never released an 0.21-20; are there other changes you did after 0.21-19 that were never released? I guess it would be good to see them; is that why you started with the old code, or was it just because you had build issues with the github code?
    
    3. the build system could do with a big overhaul, if only someone more competent than me wanted to do it. But I'm not keen on removing local help files or making changes that'll cause work for downstream packagers without a clear rationale.
I presume you're saying you have automake problems with my source, nothing to do with your new changes. I thought the build system was working fairly well for other people, although I think on Arch they've found they need to use some special flags for the latest gcc or something.
I'd be interested to see the problems you're getting; It doesn't sound like you've downloaded using git and not found the instructions to run autoreconf -i, which is what trips some people up.
    
    4. I did look into what was required to port to GTK3 several years ago. It seemed like it wouldn't be too hard, but I haven't been able to justify investing the time.

**Comment by AlisterH** [comment]
If you're keen to look at that then go for it.  I do like the "eye candy" and I've actually found it useful when debugging in some cases.  
If you're investing a lot of time in it you might want to look at whether you can replace that code with something more future proof.  Maybe an option is the "gtkvumeter" code - it has been used in several projects and I see in buzztrax they've ported it to cairo and now gtk3.

BTW I'm not sure that I'll ever get around to it, but the one enhancement I'd really like to look at is giving the user better information if they are trying to adjust L-R balance, i.e. use something like libebur128 to measure the loudness of each channel separately (treating that channel as "dual mono"), and report that to the user, along with the maximum amplification without clipping, and I think the maximum "momentary loudness" and "true peak".  If we did add a dependency on libebur128 it would also be nice to use it to calculate something more meaningful ("momentary loudness" or "true peak") to show with the ledbar.

**Comment by weltyj** [comment]
This is a horrid way to do a backup, but faster than github.  I have to run out soon, and wanted to get the work to you.  These are changes from 0.22-04.

Ledbar now tracks with playback, and there is a "memory" of the maximum level from the previous 0.9 second of playback (currently hardcoded a previous 40960 samples).  It was easy to add the memory because I had to save max level data for all playback blocks to get the led levels synchronized with the audio being played on the device.   The memory really should be smarter about the # blocks to scan for previous maximum level to get a 1 second review.

I fixed a number of unused variables, and explained a few things in audio_util.c as well as cleaning up some of that code.

Oh, I tried to double click in the audio window to select everything in view which I am so used to doing now in windows, it didn't work because it was never coded, I coded that into drawing.c

I'll do a proper gitub pull request later.

Cheers!
Jeff








On Monday, January 18, 2021, 3:47:16 PM PST, AlisterH <notifications@github.com> wrote: 







If you're keen to look at that then go for it. I do like the "eye candy" and I've actually found it useful when debugging in some cases.
If you're investing a lot of time in it you might want to look at whether you can replace that code with something more future proof. Maybe an option is the "gtkvumeter" code - it has been used in several projects and I see in buzztrax they've ported it to cairo and now gtk3.

BTW I'm not sure that I'll ever get around to it, but the one enhancement I'd really like to look at is giving the user better information if they are trying to adjust L-R balance, i.e. use something like libebur128 to measure the loudness of each channel separately (treating that channel as "dual mono"), and report that to the user, along with the maximum amplification without clipping, and I think the maximum "momentary loudness" and "true peak". If we did add a dependency on libebur128 it would also be nice to use it to calculate something more meaningful ("momentary loudness" or "true peak") to show with the ledbar.
