### ISSUE TITLE
Enhancement request: Allow zoom during playback

### ISSUE THREAD

**Issue by martin-ward** [AlisterH/gwc#26]
Now that we can once again select during playback, would it also be possible to allow "Zoom in on selected portion" to work during playback?

This can stop playback and zoom in: it just saves an extra click during editing :-)

**Comment by AlisterH** [comment]
If it is helpful we could make just about everything work the same way.

**Comment by AlisterH** [comment]
If you're trying to save clicks, are you aware that you can configure keyboard shortcuts for tools that don't have them by default, if you put `gtk-can-change-accels=1` in your GTK2 settings (e.g. ~/.gtkrc-2.0)?

N.B. If you try to change existing shortcuts be aware that in some cases it won't work at the moment - we need to rework some code that hard-codes shortcuts.
