### ISSUE TITLE
gcc version 10.3.0 (GNU Binutils 2.35.2) gives errors about "multiple definitions"

### ISSUE THREAD

**Issue by martin-ward** [AlisterH/gwc#28]
...
/bin/ld: pinknoise.o:/home/martin/src.lib/gwc-allow_select_during_playback_v2/gwc.h:188: multiple definition of `tmpdir'; reverb.o:/home/martin/src.lib/gwc-allow_select_during_playback_v2/gwc.h:188: first defined here
/bin/ld: biquad.o:/home/martin/src.lib/gwc-allow_select_during_playback_v2/gwc.h:193: multiple definition of `main_window'; reverb.o:/home/martin/src.lib/gwc-allow_select_during_playback_v2/gwc.h:193: first defined here
/bin/ld: biquad.o:/home/martin/src.lib/gwc-allow_select_during_playback_v2/gwc.h:189: multiple definition of `CLIPBOARD_FILE'; reverb.o:/home/martin/src.lib/gwc-allow_select_during_playback_v2/gwc.h:189: first defined here
/bin/ld: biquad.o:/home/martin/src.lib/gwc-allow_select_during_playback_v2/gwc.h:188: multiple definition of `tmpdir'; reverb.o:/home/martin/src.lib/gwc-allow_select_during_playback_v2/gwc.h:188: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:735: gwc] Error 1

A workaround is to edit the Makefile after running ./configure and add these options to the LDFLAGS line:

LDFLAGS = -Xlinker --allow-multiple-definition

**Comment by AlisterH** [comment]
Unless I'm missing something that's easy to fix.  Thanks for the report.

**Comment by AlisterH** [comment]
BTW you can also run `./configure LDFLAGS='-Xlinker --allow-multiple-definition'` or `make LDFLAGS='-Xlinker --allow-multiple-definition'`

**Comment by AlisterH** [comment]
Classic; I was doing exactly the same changes as the Debian guys had already done in their system, before thinking of checking if they had a patch.  I wish they'd send things like this upstream.
Fixed in latest commit to both master and "stable" branch.
