### ISSUE TITLE
Missing configure file. Cannot build Linux.

### ISSUE THREAD

**Issue by lahtis** [AlisterH/gwc#29]
There is not configure files in Linux?
Readme file say.

Installation
------------
If you are using a release source tarball, extract it (tar -xvzf <...>).
Enter the directory created.
Run "./configure".
Run "make".
Run "make install".

**Comment by AlisterH** [comment]
Sorry, it looks like you have found a readme that is quite out of date - is it on the sourceforge page somewhere?
The current Readme says:
```
Installation
------------
If you are using a release source tarball, extract it (tar -xvzf <...>).
Enter the directory created.
Run "autoreconf -i" (shouldn't be necessary if you are using a release tarball)
Run "./configure".
Run "make".
Run "make install".

**Comment by AlisterH** [comment]
Oh - no, I see the install file has got out of sync between master and stable.
What I posted was from master - stable branch says it too, but down below.  I think I moved it up in master because people tend to overlook it

**Comment by lahtis** [comment]
"In case you are building the source from git you will first need to run "autoreconf -i""

Thanks for info. Again, I learned something new.
