### ISSUE TITLE
Building not working. 

### ISSUE THREAD

**Issue by lahtis** [AlisterH/gwc#30]
Ubuntu 18.04 LTS, 
5.4.0-107-generic #121~18.04.1-Ubuntu SMP Thu Mar 24 17:21:33 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

1. Copy GitHub Master source
2. autoreconf -i

Warnings aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'

3. ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for SNDFILE... yes
checking for PULSEAUDIO... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking for cos in -lm... yes
checking for ogg... disabled
checking for mp3... disabled
checking for ALSA... yes
checking Pulse Audio enabled... no
checking for fftw_plan_r2r_1d in -lfftw3... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking sndfile.h usability... yes
checking sndfile.h presence... yes
checking for sndfile.h... yes
checking whether time.h and sys/time.h may both be included... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for GTK... yes
checking whether gcc needs -traditional... no
checking return type of signal handlers... void
checking for vprintf... yes
checking for _doprnt... no
checking for gettimeofday... yes
checking for Mac OS X platform... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands

4. make
make: *** No rule to make target 'err.h', needed by 'copy.o'. Stop
[autoscan.log](https://github.com/AlisterH/gwc/files/8496199/autoscan.log)

**Comment by AlisterH** [comment]
Thanks.  I can try to investigate, but maybe not until some time next week.  I'm not an expert with these build tools, but I have a vague idea that I've dealt with this error before.

Would you be able to package (zip, tarball, whatever) your build directory and upload it somewhere?
You can successfully build the release, can't you?  Maybe you could upload a successful build directory, too.

**Comment by AlisterH** [comment]
Of course, there haven't been any changes to the build system recently, so if you have issues with autoreconf  it should be easy to workaround them by just copying the latest source over the last release source.

But it would be nice to solve the issues instead.

**Comment by lahtis** [comment]
Something is diffrent in github and sourceforge versions. Sourceforge version can build. But github version not.

**Comment by AlisterH** [comment]
Nothing is different.  I have tested downloading from both sites and the downloads are binary identical.
I suspect you are not downloading the actual release from github.  This is the actual release:
![screenie](https://user-images.githubusercontent.com/714600/164967681-96189ec1-b47a-444a-8a4c-65f8eb30e09e.png)

If I remember correctly, the two links labelled "Source code" are just github automatically packaging what is in git, the same as if you go to https://github.com/AlisterH/gwc/tree/0.22-05 and click "Code>Download Zip".  So they don't include a configure script or anything that is generated by `make dist`, and they include _everything_ that is in git, whereas `make dist` excludes some of the junk that isn't needed.

**Comment by AlisterH** [comment]
> If I remember correctly, the two links labelled "Source code" are just github automatically packaging what is in git, the same as if you go to https://github.com/AlisterH/gwc/tree/0.22-05 and click "Code>Download Zip". So they don't include a configure script or anything that is generated by `make dist`, and they include _everything_ that is in git, whereas `make dist` excludes some of the junk that isn't needed.

In case you're wondering, I can't see a way to configure github to disable or hide these "source" packages.

**Comment by AlisterH** [comment]
Testing building from git on Ubuntu 18.04, I do not encounter this problem.
The error message suggests meschach/err.h was deleted from your build directory or something.  It will be hard to debug without access to your system.

**Comment by AlisterH** [comment]
Closing for now, but I'm quite happy to reopen if someone provides a failing build directory or identifies an environment where this problem can be reproduced.
